name: Deploy to EC2 (Angular SSR)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular SSR
        run: npm run build:ssr

      - name: Package build
        run: |
          mkdir -p release
          cp -r dist release/dist
          cp ecosystem.config.cjs release/
          tar -czf release.tar.gz -C release .

      - name: Copy to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          source: "release.tar.gz"
          target: "/var/www/your-app/"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          script: |
            cd /var/www/your-app
            tar -xzf release.tar.gz
            rm -f release.tar.gz
            . ~/.nvm/nvm.sh
            pm2 startOrReload ecosystem.config.cjs
            pm2 save
